# Lumina Linux — systemd-boot entry (UEFI)
# Located on the EFI system partition at /loader/entries/lumina.conf

title   Lumina Linux (x86_64, UEFI)
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/intel-ucode.img
initrd  /arch/boot/amd-ucode.img
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=arch archisolabel=LUMINA_%ARCHISO_LABEL_SUF%
