# Lumina Linux — Calamares welcome module
---
showSupportUrl: true
supportUrl: https://github.com/salom600/links/issues
showKnownIssuesUrl: true
knownIssuesUrl: https://github.com/salom600/links/issues
showReleaseNotesUrl: true
releaseNotesUrl: https://github.com/salom600/links/releases

# Requirements check: ensure we have enough RAM and disk
requiredStorage: 16
requiredRam: 1.5
internetCheckUrl: https://github.com
check: true
required:
  - storage
  - ram
  - root
